### PR TITLE
Fix issue when adding a team member that was not in classroom

### LINKED ISSUE #56: [API] Don't allow user to be added to team without being a member of the classroom
Currently, the API allows teachers to add any user to a team, even if they aren't members of the classroom. There should be an error associated to this situation.

### PR DESCRIPTION
**Pull request by PTKay**
This PR fixes an issue where the API allowed users to be added to a team, even if said users were not in the classroom.

Closes GH-56.

### CODE REVIEW

File: code/jvm/src/main/kotlin/org/ionproject/codegarten/controllers/api/UsersController.kt [hunk 1]
```diff
@@ -332,8 +334,13 @@ class UsersController(
     ): ResponseEntity<Any> {
         if (userClassroom.role != TEACHER) throw ForbiddenException("User is not a teacher")
 
+        val userToAddMembership = usersDb.getUserMembershipInClassroom(orgId, classroomNumber, userId)
+        if (userToAddMembership.role == NOT_A_MEMBER) {
+            throw InvalidInputException("Cannot add a user that's not a classroom member")
```
Comment (TiagoMMDavid) [inline code/jvm/src/main/kotlin/org/ionproject/codegarten/controllers/api/UsersController.kt]: I believe the exception being thrown should be a `ForbiddenException` instead

**Review by TiagoMMDavid — CHANGES_REQUESTED** [review]
Left a comment about the Exception

**Review by TiagoMMDavid — APPROVED** [review]
